[tool.black]
line-length = 120
exclude = '''/(
    docs/
)'''

[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 120
include_trailing_comma = true
skip = [
    "docs/",
]

[tool.mypy]
disallow_untyped_calls = true
explicit_package_bases = true
ignore_missing_imports = true
install_types = true
exclude = [
    "^docs/",
]

[tool.pytest.ini_options]
pythonpath = ["./src", "./test"]
python_files = "test/**.py"